### PR TITLE
Added rules

### PR DESCRIPTION
**Pull request by babdab9**
@binuwu can u see the rules? imma give u write access on em

### CODE REVIEW

**Comment by binuwu** [comment]
I can't merge this because you reverted important and core fixes from yesterday, meaning we'll jump back two versions.

**Comment by babdab9** [comment]
I rebased merged, didnt liked it n reverted, made a erge commit and added smth

**Comment by babdab9** [comment]
I think u should see my pr's on my fork @binuwu

**Comment by binuwu** [comment]
can i merge this?

**Comment by babdab9** [comment]
JUST MERGE ALREADY @binuwu

**Comment by binuwu** [comment]
will this heck any of the code?

**Comment by babdab9** [comment]
u got me dammit

**Comment by binuwu** [comment]
aaa i hope no code is lost

**Pull request merged**
