### PR TITLE
Redesigned README.md

### PR DESCRIPTION
**Pull request by babdab9**
Please, all comments should be dm'ed to me: ThatGreekGuy#7780

### CODE REVIEW

**Comment by binuwu** [comment]
owo

**Comment by babdab9** [comment]
reeeeee webhooks

**Comment by box6969** [comment]
im gay

**Comment by MegaHello** [comment]
Are you? Can we get married?

**Comment by box6969** [comment]
gtfo i have a boyfriend

**Comment by MegaHello** [comment]
i want to join the Private Beta of filebin. How i join it?

**Comment by box6969** [comment]
gucci gang gucci gang gucci gang gucci gang gucci gang gucci gang gucci gang

**Comment by MercerMrc** [comment]
To MegaHello: ''Where can I get some of this juicy stuff?
We're currently in an in-private beta you can join just by shooting me a DM and asking, there aren't really any requirements to get in other than to be cool and not to upload/shorten illegal shit''

**Comment by babdab9** [comment]
A. ALL REQUESTS TO JOIN SHOULD BE ENCLOSED TO AN ISSUE
B. STOP SHITPOSTING

**Comment by MercerMrc** [comment]
^^
that thb

**Comment by box6969** [comment]
mercer gay i code pascal for minecraft inc!!!11!11

**Comment by MercerMrc** [comment]
can you like stop shitposting maybe, ill laugh if bin gets triggerd

**Comment by box6969** [comment]
ok soz im new to github so idk what to post here xD
wheres the button to send memes btw

**Comment by babdab9** [comment]
@box6969 @MercerMrc please stop discussing in here. This is from now on monitored

**Pull request merged**
